# install needed plugins
required_plugins = %w(vagrant-share vagrant-vbguest)
plugins_to_install = required_plugins.select { |plugin| not Vagrant.has_plugin? plugin }

if not plugins_to_install.empty?
  puts "Installing plugins: #{plugins_to_install.join(' ')}"
  if system "vagrant plugin install #{plugins_to_install.join(' ')}"
    exec "vagrant #{ARGV.join(' ')}"
  else
    abort "Installation of one or more plugins has failed. Aborting."
  end
end

# FIX VBGUEST : 
# file : C:\Users\gdagraca\.vagrant.d\gems\2.4.9\gems\vagrant-vbguest-0.22.1\lib\vagrant-vbguest
# replace `unmae -r` by amd64

VAGRANT_HOME="/home/vagrant/"

Vagrant.configure("2") do |config|
  # config.vm.box = "debian/jessie64"
  config.vm.box = "debian/stretch64"
  
  config.vm.define "java" do |java|
  end
    
  # ssh configuration
  config.vm.provision "copy ssh configuration", type: "file", source: "~/.ssh", destination: "/home/vagrant/.ssh"
  
  config.vm.provision "prepare ssh configuration", type: "shell", inline: <<-SHELL 
	chmod 755 /home/vagrant/.ssh
	chmod 600 /home/vagrant/.ssh/*
  SHELL
     
  # Add Development tools
  config.vm.provision "install tools", type: "shell", inline: <<-SHELL
	 export DEBIAN_FRONTEND=noninteractive
	 echo -e 'Dpkg::Progress-Fancy "1";\nAPT::Color "1";' > /etc/apt/apt.conf.d/99progressbar
	 #get the last informations from repository
	 sudo apt-get -y install curl
	 sudo apt-get -y install apt-transport-https
     

	 # prepare VsCode
	 curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
	 sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
	 sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
	 
	 sudo apt-get -y update # >/dev/null 2>&1
	 #sudo apt-get dist-upgrade -y
	 sudo /sbin/rcvboxadd quicksetup all
	 sudo apt-get -y -q install code libxss1 git chromium chromium-l10n # >/dev/null 2>&1
	 
	 # JAVA
	 sudo apt-get -y -q install openjdk-8-jre openjdk-8-jdk maven

	 #### LXQT ###
     sudo apt-get -y install lightdm
	 sudo apt-get -y install xfonts-base xserver-xorg-input-all xinit xserver-xorg xserver-xorg-video-all
	 sudo apt-get -y install --no-install-recommends lxde-core
	 #update components
	 #sudo apt-get -y dist-upgrade # >/dev/null 2>&1
	 ### CLEAN ###
	 sudo apt-get autoremove -y
	 # auto login with lightdm
     echo "autologin-user=vagrant" | tee --append /usr/share/lightdm/lightdm.conf.d/01_debian.conf
	 # add suoders
	 adduser vagrant sudo >/dev/null 2>&1
	 # french keyboard
     sudo sed --in-place s/us/fr/g /etc/default/keyboard
	 # restart system
     systemctl reboot
   SHELL

  config.vm.network "forwarded_port", guest: 8080, host: 8889
    
  # Declare provider
  config.vm.provider 'virtualbox' do |vb|
	vb.gui = true
	vb.memory = '2048'
    vb.cpus = '2'
    #vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    vb.customize ["modifyvm", :id, "--vram", "12"]
  end
end
