# install needed plugins
required_plugins = %w(vagrant-share vagrant-vbguest)
plugins_to_install = required_plugins.select { |plugin| not Vagrant.has_plugin? plugin }

if not plugins_to_install.empty?
  puts "Installing plugins: #{plugins_to_install.join(' ')}"
  if system "vagrant plugin install #{plugins_to_install.join(' ')}"
    exec "vagrant #{ARGV.join(' ')}"
  else
    abort "Installation of one or more plugins has failed. Aborting."
  end
end

VAGRANT_HOME="/home/vagrant/"

Vagrant.configure("2") do |config|

  config.vm.box = "debian/stretch64"
  
  config.vm.define "node" do |node|
  end
  
  config.vm.provision "copy ssh configuration", type: "file", source: "~/.ssh", destination: "/home/vagrant/.ssh"
  
  config.vm.provision "prepare ssh configuration", type: "shell", inline: <<-SHELL 
	chmod 755 /home/vagrant/.ssh
	chmod 600 /home/vagrant/.ssh/*
  SHELL
     
  # Add Development tools
  config.vm.provision "install tools", type: "shell", inline: <<-SHELL
	export DEBIAN_FRONTEND=noninteractive
	echo -e 'Dpkg::Progress-Fancy "1";\nAPT::Color "1";' > /etc/apt/apt.conf.d/99progressbar
	
    sudo apt-get --quiet update
    sudo apt-get --assume-yes upgrade
	
	#prepare minimum tools
	sudo apt-get -y -q install curl #wget

	#prepare Node
	curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
	
	#prepare VsCode
	curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
	sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
	sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'

	#prepare PostGreSQL
	#sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
	#sudo curl -s https://www.postgresql.org/media/keys/ACCC4CF8.asc --progress-bar | gpg --dearmor > pgdg.gpg
	#sudo mv pgdg.gpg /etc/apt/trusted.gpg.d/pgdg.gpg

	# install tools
	sudo apt-get -y -q install apt-transport-https nodejs  code git chromium chromium-l10n # >/dev/null 2>&1 libxss1 postgresql-10
	#### LXQT ###
	sudo apt-get -y -qq install xfonts-base xserver-xorg-input-all xinit xserver-xorg xserver-xorg-video-all lightdm
	sudo apt-get -y -qq install --no-install-recommends lxde-core
	### CLEAN ###
	sudo apt-get autoremove -y	 
	# change code as default editor
	sudo update-alternatives --set editor /usr/bin/code
	# auto login with lightdm
	echo "autologin-user=vagrant" | tee --append /usr/share/lightdm/lightdm.conf.d/01_debian.conf
	# add suoders
	adduser vagrant sudo >/dev/null 2>&1
	# french keyboard
	sudo sed --in-place s/us/fr/g /etc/default/keyboard
	# restart system
	systemctl reboot
   SHELL
  
  config.vm.network "forwarded_port", guest: 8080, host: 8888
    
  # Declare provider
  config.vm.provider 'virtualbox' do |vb|
	vb.gui = true
	vb.memory = '2048'
    vb.cpus = '2'
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    vb.customize ["modifyvm", :id, "--vram", "12"]
  end
end
